[package]
name = "repl"
version.workspace = true
edition.workspace = true

[dependencies]
gelite-commands = { path = "../gelite-commands" }
query-ast = { path = "../../engine/query-ast" }
query-parser = { path = "../../engine/query-parser" }
schema-model = { path = "../../engine/schema-model" }
sqlite-runner = { path = "../../engine/sqlite-runner" }
rustyline = "18"

[dev-dependencies]
sqlite-query-sqlgen = { path = "../../engine/sqlite-query-sqlgen" }
sqlite-runner = { path = "../../engine/sqlite-runner", features = ["native"] }
uuid = { version = "1.24.0", features = ["v4"] }
